// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@acme/orm/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@acme/orm/contract/types';

export type StorageHash =
  StorageHashBase<'3a6ffdf836b1e29fd2ffd8b5118ffd732a87d461bce83b11b0e4dfb4db396a0b'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly thing: {
              columns: {
                readonly id: {
                  readonly dataType: 'acme/int4';
                  readonly codecId: 'sql/int@1';
                  readonly nullable: false;
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
};
