// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-postgres/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'9badeaec2e56b0e1a85e575799922686ce1915f9087c2d37714def6a92740843'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly setting: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/jsonb@1', { readonly codecId: 'pg/text@1'; readonly nativeType: 'text' }>;
                  };
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
};
