// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@acme/orm/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@acme/orm/contract/types';

export type StorageHash =
  StorageHashBase<'c8a500bce17514ecce4c3638f7e3e0447ac842502b8480d32725fdcc5141aa6d'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly thing: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'sql/int@1';
                  readonly nullable: false;
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
};
