// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-sqlite/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'9df4e74652f749c2f4006615728f0bf1b589cb7b30a4159211c4661d0af93109'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly setting: {
              columns: {
                readonly id: {
                  readonly dataType: 'sqlite/integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', '0'>;
                  };
                };
                readonly count: {
                  readonly dataType: 'sqlite/integer';
                  readonly codecId: 'sql/int@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sql/int@1', '42'>;
                  };
                };
                readonly big: {
                  readonly dataType: 'sqlite/integer';
                  readonly codecId: 'sqlite/bigint@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/bigint@1', '9007199254740993'>;
                  };
                };
                readonly small: {
                  readonly dataType: 'sqlite/integer';
                  readonly codecId: 'sqlite/bigintnumber@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/bigintnumber@1', '-7'>;
                  };
                };
                readonly doc: {
                  readonly dataType: 'sqlite/text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', '{"a":[true,null],"b":1}'>;
                  };
                };
                readonly label: {
                  readonly dataType: 'sqlite/text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', '"it\'s"'>;
                  };
                };
                readonly empty: {
                  readonly dataType: 'sqlite/text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', 'null'>;
                  };
                };
                readonly name: {
                  readonly dataType: 'sqlite/text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'unnamed'>;
                  };
                };
                readonly ratio: {
                  readonly dataType: 'sqlite/real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/real@1', 1.5>;
                  };
                };
                readonly seenAt: {
                  readonly dataType: 'sqlite/text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly payload: {
                  readonly dataType: 'sqlite/blob';
                  readonly codecId: 'sqlite/blob@1';
                  readonly nullable: true;
                };
                readonly code: {
                  readonly dataType: 'sqlite/character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                };
                readonly tag: {
                  readonly dataType: 'sqlite/character-varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                };
                readonly score: {
                  readonly dataType: 'sqlite/real';
                  readonly codecId: 'sql/float@1';
                  readonly nullable: true;
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
};
