// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-postgres/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'4a96b488a4ce92b434e5f7d6607b6435c0955f0d36b0018077045787764240e6'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {

          };
        };
      };
    };
    readonly types: {
      readonly vector: {
        readonly kind: 'codec-instance';
        readonly codecId: 'pg/vector@1';
        readonly dataType: 'pgvector/vector';
        readonly typeParams: Record<string, never>;
      };
    };
    readonly storageHash: StorageHash;
  };
};
