// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-sqlite/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'66a408f76796db73433c83fbd088c87d168b3800d3f0a737059e3c1f8fd013b0'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly lamp: {
              columns: {
                readonly id: {
                  readonly dataType: 'sqlite/integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly shade: {
                  readonly dataType: 'sqlite/text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', '"low"'>;
                  };
                  readonly valueSet: { readonly plane: 'storage'; readonly entityKind: 'valueSet'; readonly namespaceId: 'public'; readonly entityName: 'Shade' };
                };
              };
            };
          };
          readonly valueSet: {
            readonly Shade: {
              readonly kind: 'valueSet';
              readonly values: readonly ['"low"', '1', 'true', 'null'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly enum: {
          readonly Shade: {
            readonly codecId: 'sqlite/json@1';
            readonly members: readonly [
              { readonly name: 'Low'; readonly value: '"low"' },
              { readonly name: 'Level'; readonly value: '1' },
              { readonly name: 'On'; readonly value: 'true' },
              { readonly name: 'Unset'; readonly value: 'null' },
            ];
          };
        };
      };
    };
  };
};
