// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-sqlite/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'4f20c9f9047b394c4018e94a5e6538e6b4bd30b46604c73d84a4bbd3c12b5b8e'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly setting: {
              columns: {
                readonly id: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 0>;
                  };
                };
                readonly count: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sql/int@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sql/int@1', 42>;
                  };
                };
                readonly big: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/bigint@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/bigint@1', '9007199254740993'>;
                  };
                };
                readonly small: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/bigintnumber@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/bigintnumber@1', -7>;
                  };
                };
                readonly doc: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', { readonly a: readonly [true, null]; readonly b: 1 }>;
                  };
                };
                readonly label: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', "it's">;
                  };
                };
                readonly empty: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/json@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/json@1', null>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'unnamed'>;
                  };
                };
                readonly ratio: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/real@1', 1.5>;
                  };
                };
                readonly seenAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: true;
                };
                readonly payload: {
                  readonly nativeType: 'blob';
                  readonly codecId: 'sqlite/blob@1';
                  readonly nullable: true;
                };
                readonly code: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                };
                readonly tag: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                };
                readonly score: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sql/float@1';
                  readonly nullable: true;
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
};
