// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-postgres/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'90ad54a8bc204f3991426b445dcc4c89a1401f51f95c3ba815fbc68fd140df97'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly thing: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly shape: {
                  readonly nativeType: 'shape';
                  readonly codecId: 'acme/shape@1';
                  readonly nullable: true;
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
};
