// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-postgres/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'eb71bcdad05720d5faa9c875ab24d8e7247fcc24dbc9294d70d170808768f871'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly post: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'sql/int@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'pg/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 203 };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly role: {
                  readonly nativeType: 'Role';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'Role' };
                };
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
  readonly extensions: {
    readonly pgvector: {
      readonly familyId: 'sql';
      readonly id: 'pgvector';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'PgVectorTypes';
            readonly named: 'CodecTypes';
            readonly package: '@prisma/orm-extension-pgvector/codec-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'vector';
            readonly targetId: 'postgres';
            readonly typeId: 'pg/vector@1';
          },
        ];
      };
    };
  };
};
