import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import stripAnsi from 'strip-ansi';
import { expect } from 'vitest';
import { type JourneyContext, runDbVerify } from '../../utils/journey-test-helpers';

export const SEED_SQL = `
  CREATE SCHEMA secure;
  CREATE TABLE secure.owners (
    id int4 PRIMARY KEY
  );

  CREATE TABLE users (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    balance numeric,
    precise_balance numeric(10,2),
    birth_date date,
    tags text[] NOT NULL DEFAULT '{}'::text[],
    labels text[] DEFAULT '{}'::text[],
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    fee numeric(10,2) NOT NULL DEFAULT 1.50,
    joined_at timestamp(3) NOT NULL DEFAULT '2024-01-01 00:00:00'
  );
  CREATE INDEX users_metadata_gin_idx ON users USING gin (metadata);
  CREATE INDEX users_email_lower_idx ON users (lower(email));
  CREATE INDEX users_email_active_idx ON users (email) WHERE (birth_date IS NULL);
  CREATE UNIQUE INDEX users_email_ci_key ON users (lower(email));
  CREATE UNIQUE INDEX users_email_plain_key ON users (email);
  CREATE INDEX users_email_ff_idx ON users (email) WITH (fillfactor = 70);
  CREATE ROLE fidelity_app_user;
  CREATE ROLE fidelity_auditor;
  ALTER TABLE users ENABLE ROW LEVEL SECURITY;
  CREATE POLICY users_owner_read ON users
    AS PERMISSIVE FOR SELECT TO fidelity_app_user
    USING (id = 1);
  CREATE POLICY "Users restrictive write" ON users
    AS RESTRICTIVE FOR UPDATE TO fidelity_app_user, fidelity_auditor
    USING (id = 1) WITH CHECK (id = 2);

  CREATE TABLE sessions (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int4 NOT NULL REFERENCES users(id),
    owner_ref int4 REFERENCES secure.owners(id)
  );

  CREATE TABLE identities (
    id serial PRIMARY KEY,
    user_id int4 NOT NULL UNIQUE REFERENCES users(id),
    provider text NOT NULL
  );
  CREATE INDEX identities_provider_hash_idx ON identities USING hash (provider);

  CREATE TABLE accounts (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    primary_user_id int4 NOT NULL UNIQUE REFERENCES users(id),
    backup_user_id int4 REFERENCES users(id)
  );

  CREATE TABLE categories (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_id int4 UNIQUE REFERENCES categories(id)
  );
`;

export function readContractPsl(ctx: JourneyContext): string {
  return readFileSync(join(ctx.testDir, 'contract.prisma'), 'utf-8');
}

export function writeContractPsl(ctx: JourneyContext, psl: string): void {
  writeFileSync(join(ctx.testDir, 'contract.prisma'), psl, 'utf-8');
}

/** Removes the bare, `@relation`-less 1:1 back-relation field infer prints on `Users`. */
export function fixOneToOneBackRelation(psl: string): string {
  return psl.replace(/^\s*identities\s+Identities\?\s*$\n/m, '');
}

/** Strips the non-btree `type:` argument infer prints on both `@@index` attributes. */
export function fixIndexTypes(psl: string): string {
  return psl.replace(/,\s*type: "(?:gin|hash)"/g, '');
}

/**
 * Asserts a pulled schema verifies clean immediately.
 *
 * `contract infer` emits `@noCheck(elementNotNull)` for every list column
 * whose live database does not carry the derived, wire-named element-non-null
 * check, so the emitted contract declares exactly what the database enforces
 * and `db verify --schema-only` exits 0 with zero issues right after
 * infer -> emit.
 */
export async function expectVerifiesCleanAfterPull(
  ctx: JourneyContext,
  subject: string,
): Promise<void> {
  const result = await runDbVerify(ctx, ['--schema-only']);
  const output = `${stripAnsi(result.stderr)}\n${stripAnsi(result.stdout)}`;
  expect(result.exitCode, `${subject}: db verify --schema-only\n${output}`).toBe(0);
  expect(output, `${subject}: verify reported issues after a pull`).not.toMatch(
    /✖ (?:missing|extra):/,
  );
}
