// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
import type { CodecTypes } from '@prisma/orm-sqlite/target/codec-types';
import type { ProfileHashBase, StorageHashBase } from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'73264bd00bf86a4bb8a0a329d31d577149a05b9a267fe7679df22aaa2b7e8dbe'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type Contract = {
  readonly storage: {
    readonly namespaces: {
      readonly public: {
        readonly entries: {
          readonly table: {
            readonly post: {
              columns: {
                readonly id: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly priority: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 1>;
                  };
                  readonly valueSet: { readonly plane: 'storage'; readonly entityKind: 'valueSet'; readonly namespaceId: 'public'; readonly entityName: 'Priority' };
                };
                readonly level: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sql/int@1';
                  readonly nullable: true;
                  readonly valueSet: { readonly plane: 'storage'; readonly entityKind: 'valueSet'; readonly namespaceId: 'public'; readonly entityName: 'Level' };
                };
                readonly mood: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                  readonly valueSet: { readonly plane: 'storage'; readonly entityKind: 'valueSet'; readonly namespaceId: 'public'; readonly entityName: 'Mood' };
                };
              };
            };
          };
          readonly valueSet: {
            readonly Level: {
              readonly kind: 'valueSet';
              readonly values: readonly [-1, 0];
            };
            readonly Mood: {
              readonly kind: 'valueSet';
              readonly values: readonly ['calm'];
            };
            readonly Priority: {
              readonly kind: 'valueSet';
              readonly values: readonly [1, 2];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly enum: {
          readonly Level: {
            readonly codecId: 'sql/int@1';
            readonly members: readonly [
              { readonly name: 'Debug'; readonly value: -1 },
              { readonly name: 'Info'; readonly value: 0 },
            ];
          };
          readonly Mood: {
            readonly codecId: 'sqlite/text@1';
            readonly members: readonly [
              { readonly name: 'Calm'; readonly value: 'calm' },
            ];
          };
          readonly Priority: {
            readonly codecId: 'sqlite/integer@1';
            readonly members: readonly [
              { readonly name: 'Low'; readonly value: 1 },
              { readonly name: 'High'; readonly value: 2 },
            ];
          };
        };
      };
    };
  };
};
