/**
 * Writes the `before` and `after` fixture projects the upgrade script's tests read, computing every hash with the live framework functions. Run it in `test/integration` with `pnpm exec tsx test/upgrade-instructions/data-type-in-contract/generate-fixtures.ts`, then `pnpm lint:fix`. It holds only while the script is pending: at release it is frozen or deleted with the hash test (see step 4 of `skills-contrib/record-upgrade-instructions/SKILL.md`).
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { canonicalizeContractToObject, computeStorageHash } from '@internal/contract/hashing';
import type { Contract } from '@internal/contract/types';
import { canonicalizeJson } from '@internal/framework-components/utils';
import { computeMigrationHash } from '@internal/migration-tools/hash';
import { sqlContractCanonicalizationHooks } from '@internal/sql-contract/canonicalization-hooks';
import { dirname, join } from 'pathe';

type Format = 'old' | 'new';
type Json = null | boolean | number | string | readonly Json[] | { readonly [key: string]: Json };
type JsonObject = { readonly [key: string]: Json };

interface ColumnSpec {
  readonly name: string;
  readonly codecId: string;
  readonly nativeType: string;
  readonly dataType: string;
  readonly nullable: boolean;
  readonly typeParams?: JsonObject;
  readonly typeRef?: string;
  readonly valueSet?: string;
  readonly functionDefault?: string;
  readonly literalDefault?: {
    readonly old: Json;
    readonly new: Json;
    readonly oldTs: string;
    readonly newTs: string;
  };
}

interface TypeSpec {
  readonly name: string;
  readonly codecId: string;
  readonly nativeType: string;
  readonly dataType: string;
  readonly typeParams?: JsonObject;
}

interface EnumSpec {
  readonly name: string;
  readonly codecId: string;
  readonly members: readonly {
    readonly name: string;
    readonly old: Json;
    readonly new: Json;
    readonly oldTs: string;
    readonly newTs: string;
  }[];
}

interface ContractSpec {
  readonly target: 'postgres' | 'sqlite' | 'acme';
  readonly tables: Readonly<Record<string, readonly ColumnSpec[]>>;
  readonly types?: readonly TypeSpec[];
  readonly enums?: readonly EnumSpec[];
  readonly extensions?: (format: Format) => JsonObject;
  readonly layout?: 'entries' | 'tables';
}

const here = dirname(fileURLToPath(import.meta.url));
const fixturesRoot = join(here, 'fixtures');
const PROFILE_HASH = '3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2';
const STALE_HASH = 'a'.repeat(64);
const GENERATED = {
  warning: '⚠️  GENERATED FILE - DO NOT EDIT',
  message: 'This file is automatically generated by "prisma contract emit".',
  regenerate: 'To regenerate, run: prisma contract emit',
};

function typeName(spec: { nativeType: string; dataType: string }, format: Format): JsonObject {
  return format === 'old' ? { nativeType: spec.nativeType } : { dataType: spec.dataType };
}

function columnJson(column: ColumnSpec, format: Format): JsonObject {
  const value: Record<string, Json> = {
    codecId: column.codecId,
    ...typeName(column, format),
    nullable: column.nullable,
  };
  if (column.typeParams) value['typeParams'] = column.typeParams;
  if (column.typeRef) value['typeRef'] = column.typeRef;
  if (column.valueSet)
    value['valueSet'] = {
      plane: 'storage',
      entityKind: 'valueSet',
      namespaceId: 'public',
      entityName: column.valueSet,
    };
  if (column.functionDefault)
    value['default'] = { kind: 'function', expression: column.functionDefault };
  if (column.literalDefault)
    value['default'] = { kind: 'literal', value: column.literalDefault[format] };
  return value;
}

function storageJson(spec: ContractSpec, format: Format): Record<string, Json> {
  const tables: Record<string, Json> = {};
  for (const [tableName, columns] of Object.entries(spec.tables)) {
    tables[tableName] = {
      columns: Object.fromEntries(
        columns.map((column) => [column.name, columnJson(column, format)]),
      ),
      primaryKey: { columns: [columns[0]?.name ?? 'id'] },
      uniques: [],
      indexes: [],
      foreignKeys: [],
    };
  }
  const namespace =
    spec.layout === 'tables'
      ? { id: 'public', tables }
      : {
          id: 'public',
          kind: `${spec.target}-schema`,
          entries: {
            table: tables,
            ...(spec.enums
              ? {
                  valueSet: Object.fromEntries(
                    spec.enums.map((enumSpec) => [
                      enumSpec.name,
                      {
                        kind: 'valueSet',
                        values: enumSpec.members.map((member) => member[format]),
                      },
                    ]),
                  ),
                }
              : {}),
          },
        };
  const storage: Record<string, Json> = { namespaces: { public: namespace } };
  if (spec.types) {
    storage['types'] = Object.fromEntries(
      spec.types.map((type) => [
        type.name,
        {
          codecId: type.codecId,
          kind: 'codec-instance',
          ...typeName(type, format),
          ...(type.typeParams ? { typeParams: type.typeParams } : {}),
        },
      ]),
    );
  }
  return storage;
}

function storageHashOf(spec: ContractSpec, format: Format): string {
  return computeStorageHash({
    target: spec.target,
    targetFamily: 'sql',
    storage: storageJson(spec, format),
    ...sqlContractCanonicalizationHooks,
  });
}

function contractObject(spec: ContractSpec, format: Format, storageHash: string): JsonObject {
  const contract = {
    targetFamily: 'sql',
    target: spec.target,
    profileHash: PROFILE_HASH,
    roots: {},
    domain: {
      namespaces: {
        public: {
          models: {},
          ...(spec.enums
            ? {
                enum: Object.fromEntries(
                  spec.enums.map((enumSpec) => [
                    enumSpec.name,
                    {
                      codecId: enumSpec.codecId,
                      members: enumSpec.members.map((member) => ({
                        name: member.name,
                        value: member[format],
                      })),
                    },
                  ]),
                ),
              }
            : {}),
        },
      },
    },
    storage: { ...storageJson(spec, format), storageHash },
    capabilities: { sql: { returning: true } },
    extensions: spec.extensions?.(format) ?? {},
    meta: {},
  };
  const canonical = canonicalizeContractToObject(blindContract(contract), {
    schemaVersion: '1',
    serializeContract: (value) => JSON.parse(JSON.stringify(value)),
    ...sqlContractCanonicalizationHooks,
  });
  return JSON.parse(JSON.stringify({ ...canonical, _generated: GENERATED }));
}

function blindContract(value: unknown): Contract {
  return value as Contract;
}

function emittedJson(contract: JsonObject): string {
  return JSON.stringify(contract, null, 2);
}

function snapshotJson(contract: JsonObject): string {
  return `${canonicalizeJson(contract)}\n`;
}

function dtsLiteral(value: string): string {
  return `'${value}'`;
}

function dtsColumn(column: ColumnSpec, format: Format, indent: string): string {
  const lines = [
    `${indent}readonly ${column.name}: {`,
    format === 'old'
      ? `${indent}  readonly nativeType: ${dtsLiteral(column.nativeType)};`
      : `${indent}  readonly dataType: ${dtsLiteral(column.dataType)};`,
    `${indent}  readonly codecId: ${dtsLiteral(column.codecId)};`,
    `${indent}  readonly nullable: ${column.nullable};`,
  ];
  if (column.functionDefault)
    lines.push(
      `${indent}  readonly default: { readonly kind: 'function'; readonly expression: '${column.functionDefault}' };`,
    );
  if (column.literalDefault) {
    const literal = format === 'old' ? column.literalDefault.oldTs : column.literalDefault.newTs;
    lines.push(
      `${indent}  readonly default: {`,
      `${indent}    readonly kind: 'literal';`,
      `${indent}    readonly value: DefaultLiteralValue<'${column.codecId}', ${literal}>;`,
      `${indent}  };`,
    );
  }
  if (column.typeParams) {
    const params = Object.entries(column.typeParams)
      .map(([key, value]) => `readonly ${key}: ${JSON.stringify(value).replaceAll('"', "'")}`)
      .join('; ');
    lines.push(`${indent}  readonly typeParams: { ${params} };`);
  }
  if (column.typeRef) lines.push(`${indent}  readonly typeRef: '${column.typeRef}';`);
  if (column.valueSet)
    lines.push(
      `${indent}  readonly valueSet: { readonly plane: 'storage'; readonly entityKind: 'valueSet'; readonly namespaceId: 'public'; readonly entityName: '${column.valueSet}' };`,
    );
  lines.push(`${indent}};`);
  return lines.join('\n');
}

function dtsType(type: TypeSpec, format: Format): string {
  const params = type.typeParams
    ? `{ ${Object.entries(type.typeParams)
        .map(([key, value]) => `readonly ${key}: ${JSON.stringify(value)}`)
        .join('; ')} }`
    : 'Record<string, never>';
  return [
    `      readonly ${type.name}: {`,
    `        readonly kind: 'codec-instance';`,
    `        readonly codecId: '${type.codecId}';`,
    format === 'old'
      ? `        readonly nativeType: '${type.nativeType}';`
      : `        readonly dataType: '${type.dataType}';`,
    `        readonly typeParams: ${params};`,
    '      };',
  ].join('\n');
}

function contractDts(spec: ContractSpec, format: Format, storageHash: string): string {
  const facade = spec.target === 'acme' ? '@acme/orm' : `@prisma/orm-${spec.target}`;
  const tables = Object.entries(spec.tables)
    .map(([tableName, columns]) =>
      [
        `            readonly ${tableName}: {`,
        '              columns: {',
        ...columns.map((column) => dtsColumn(column, format, '                ')),
        '              };',
        '            };',
      ].join('\n'),
    )
    .join('\n');
  const types = spec.types
    ? ['    readonly types: {', ...spec.types.map((type) => dtsType(type, format)), '    };']
    : [];
  return [
    '// ⚠️  GENERATED FILE - DO NOT EDIT',
    "// This file is automatically generated by 'prisma contract emit'.",
    `import type { CodecTypes } from '${facade}/target/codec-types';`,
    `import type { ProfileHashBase, StorageHashBase } from '${facade}/contract/types';`,
    '',
    'export type StorageHash =',
    `  StorageHashBase<'${storageHash}'>;`,
    'export type ProfileHash =',
    `  ProfileHashBase<'${PROFILE_HASH}'>;`,
    'type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes',
    "  ? CodecTypes[CodecId]['output']",
    '  : _Encoded;',
    '',
    'export type Contract = {',
    '  readonly storage: {',
    '    readonly namespaces: {',
    '      readonly public: {',
    '        readonly entries: {',
    '          readonly table: {',
    tables,
    '          };',
    ...(spec.enums ? valueSetDts(spec.enums, format) : []),
    '        };',
    '      };',
    '    };',
    ...types,
    '    readonly storageHash: StorageHash;',
    '  };',
    ...(spec.enums ? domainEnumDts(spec.enums, format) : []),
    ...(spec.extensions ? extensionsDts(format) : []),
    '};',
    '',
  ].join('\n');
}

function valueSetDts(enums: readonly EnumSpec[], format: Format): string[] {
  return [
    '          readonly valueSet: {',
    ...enums.flatMap((enumSpec) => [
      `            readonly ${enumSpec.name}: {`,
      "              readonly kind: 'valueSet';",
      `              readonly values: readonly [${enumSpec.members
        .map((member) => (format === 'old' ? member.oldTs : member.newTs))
        .join(', ')}];`,
      '            };',
    ]),
    '          };',
  ];
}

function domainEnumDts(enums: readonly EnumSpec[], format: Format): string[] {
  return [
    '  readonly domain: {',
    '    readonly namespaces: {',
    '      readonly public: {',
    '        readonly enum: {',
    ...enums.flatMap((enumSpec) => [
      `          readonly ${enumSpec.name}: {`,
      `            readonly codecId: '${enumSpec.codecId}';`,
      '            readonly members: readonly [',
      ...enumSpec.members.map(
        (member) =>
          `              { readonly name: '${member.name}'; readonly value: ${format === 'old' ? member.oldTs : member.newTs} },`,
      ),
      '            ];',
      '          };',
    ]),
    '        };',
    '      };',
    '    };',
    '  };',
  ];
}

function extensionsDts(format: Format): string[] {
  return [
    '  readonly extensions: {',
    '    readonly pgvector: {',
    "      readonly familyId: 'sql';",
    "      readonly id: 'pgvector';",
    '      readonly types: {',
    '        readonly codecTypes: {',
    '          readonly import: {',
    "            readonly alias: 'PgVectorTypes';",
    "            readonly named: 'CodecTypes';",
    "            readonly package: '@prisma/orm-extension-pgvector/codec-types';",
    '          };',
    '        };',
    ...(format === 'old'
      ? [
          '        readonly storage: readonly [',
          '          {',
          "            readonly familyId: 'sql';",
          "            readonly nativeType: 'vector';",
          "            readonly targetId: 'postgres';",
          "            readonly typeId: 'pg/vector@1';",
          '          },',
          '        ];',
        ]
      : []),
    '      };',
    '    };',
    '  };',
  ];
}

interface MigrationSpec {
  readonly dir: string;
  readonly from: string | null;
  readonly to: string;
  readonly invariants?: readonly string[];
  readonly migrationTs?: boolean;
}

function migrationFiles(spec: MigrationSpec, snapshotsRelative: string): Record<string, string> {
  const ops = [
    {
      id: `migration.${spec.dir.split('/').at(-1)}`,
      label: 'Fixture operation',
      operationClass: 'additive' as const,
      execute: [{ description: 'fixture', sql: 'SELECT 1' }],
    },
  ];
  const metadata = {
    from: spec.from,
    to: spec.to,
    providedInvariants: spec.invariants ?? [],
    createdAt: '2026-01-01T00:00:00.000Z',
  };
  const files: Record<string, string> = {
    [`${spec.dir}/migration.json`]: `${JSON.stringify(
      { ...metadata, migrationHash: computeMigrationHash(metadata, ops) },
      null,
      2,
    )}\n`,
    [`${spec.dir}/ops.json`]: `${JSON.stringify(ops, null, 2)}\n`,
  };
  if (spec.migrationTs) {
    const imports = [
      `import type { Contract as End } from '${snapshotsRelative}/${spec.to}/contract';`,
      `import endContract from '${snapshotsRelative}/${spec.to}/contract.json' with { type: 'json' };`,
    ];
    if (spec.from)
      imports.push(
        `import type { Contract as Start } from '${snapshotsRelative}/${spec.from}/contract';`,
        `import startContract from '${snapshotsRelative}/${spec.from}/contract.json' with { type: 'json' };`,
      );
    files[`${spec.dir}/migration.ts`] = [
      ...imports,
      '',
      `export const contracts = { start: ${spec.from ? 'startContract' : 'null'}, end: endContract };`,
      `export type Contracts = { start: ${spec.from ? 'Start' : 'never'}; end: End };`,
      '',
    ].join('\n');
  }
  return files;
}

function ref(hash: string, invariants: readonly string[] = []): string {
  return `${JSON.stringify({ hash, invariants }, null, 2)}\n`.replace(
    /"invariants": \[\n\s+([^\n]*)\n\s+\]/,
    '"invariants": [$1]',
  );
}

function writeTree(root: string, files: Record<string, string>): void {
  for (const [path, content] of Object.entries(files)) {
    const file = join(root, path);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
}

function writeCase(name: string, build: (format: Format) => Record<string, string>): void {
  writeTree(join(fixturesRoot, name, 'before'), build('old'));
  writeTree(join(fixturesRoot, name, 'after'), build('new'));
}

function writeUnchangedCase(name: string, files: Record<string, string>): void {
  writeTree(join(fixturesRoot, name, 'before'), files);
}

interface ContractFiles {
  readonly hash: string;
  readonly contract: JsonObject;
  readonly dts: string;
}

function contractFiles(spec: ContractSpec, format: Format, storedHash?: string): ContractFiles {
  const hash = storedHash ?? storageHashOf(spec, format);
  return {
    hash,
    contract: contractObject(spec, format, hash),
    dts: contractDts(spec, format, hash),
  };
}

const pgvectorExtension = (format: Format): JsonObject => ({
  pgvector: {
    familyId: 'sql',
    id: 'pgvector',
    kind: 'extension',
    targetId: 'postgres',
    types: {
      codecTypes: {
        import: {
          alias: 'PgVectorTypes',
          named: 'CodecTypes',
          package: '@prisma/orm-extension-pgvector/codec-types',
        },
      },
      ...(format === 'old'
        ? {
            storage: [
              {
                familyId: 'sql',
                nativeType: 'vector',
                targetId: 'postgres',
                typeId: 'pg/vector@1',
              },
            ],
          }
        : {}),
    },
    version: '0.0.1',
  },
});

const postColumns: readonly ColumnSpec[] = [
  { name: 'id', codecId: 'sql/int@1', nativeType: 'int4', dataType: 'pg/int4', nullable: false },
  {
    name: 'title',
    codecId: 'pg/varchar@1',
    nativeType: 'character varying',
    dataType: 'pg/varchar',
    nullable: false,
    typeParams: { length: 203 },
  },
  {
    name: 'createdAt',
    codecId: 'pg/timestamptz@1',
    nativeType: 'timestamptz',
    dataType: 'pg/timestamptz',
    nullable: false,
    functionDefault: 'now()',
  },
  {
    name: 'role',
    codecId: 'pg/enum@1',
    nativeType: 'Role',
    dataType: 'pg/enum',
    nullable: false,
    typeParams: { typeName: 'Role' },
  },
];

const embeddingColumn: ColumnSpec = {
  name: 'embedding',
  codecId: 'pg/vector@1',
  nativeType: 'vector',
  dataType: 'pgvector/vector',
  nullable: true,
  typeRef: 'Embedding3',
};

const vectorType: TypeSpec = {
  name: 'vector',
  codecId: 'pg/vector@1',
  nativeType: 'vector',
  dataType: 'pgvector/vector',
};

const appInitial: ContractSpec = {
  target: 'postgres',
  tables: { post: postColumns },
  extensions: pgvectorExtension,
};

const appCurrent: ContractSpec = {
  target: 'postgres',
  tables: { post: [...postColumns, embeddingColumn] },
  types: [
    {
      name: 'Embedding3',
      codecId: 'pg/vector@1',
      nativeType: 'vector',
      dataType: 'pgvector/vector',
      typeParams: { length: 203 },
    },
  ],
  extensions: pgvectorExtension,
};

const pgvectorSpace: ContractSpec = { target: 'postgres', tables: {}, types: [vectorType] };

const mongoContract = `${JSON.stringify(
  {
    schemaVersion: '1',
    targetFamily: 'mongo',
    target: 'mongo',
    storage: {
      collections: {
        user: { fields: { id: { codecId: 'mongo/objectId@1', nativeType: 'objectId' } } },
      },
      storageHash: 'b'.repeat(64),
    },
  },
  null,
  2,
)}\n`;

function postgresExtensionSpace(format: Format): Record<string, string> {
  const initial = contractFiles(appInitial, format);
  const current = contractFiles(appCurrent, format);
  const vector = contractFiles(pgvectorSpace, format);
  return {
    'prisma/contract.json': emittedJson(current.contract),
    'prisma/contract.d.ts': current.dts,
    'mongo/contract.json': mongoContract,
    [`migrations/snapshots/${initial.hash}/contract.json`]: snapshotJson(initial.contract),
    [`migrations/snapshots/${initial.hash}/contract.d.ts`]: initial.dts,
    [`migrations/snapshots/${current.hash}/contract.json`]: snapshotJson(current.contract),
    [`migrations/snapshots/${current.hash}/contract.d.ts`]: current.dts,
    [`migrations/snapshots/${vector.hash}/contract.json`]: snapshotJson(vector.contract),
    [`migrations/snapshots/${vector.hash}/contract.d.ts`]: 'export {};\n',
    ...migrationFiles(
      {
        dir: 'migrations/app/20260101T0000_initial',
        from: null,
        to: initial.hash,
        migrationTs: true,
      },
      '../../snapshots',
    ),
    ...migrationFiles(
      {
        dir: 'migrations/app/20260201T0000_add_embedding',
        from: initial.hash,
        to: current.hash,
        migrationTs: true,
      },
      '../../snapshots',
    ),
    'migrations/app/refs/head.json': ref(current.hash),
    'migrations/app/refs/db.json': ref(initial.hash),
    ...migrationFiles(
      {
        dir: 'migrations/pgvector/20260601T0000_install_vector_extension',
        from: null,
        to: vector.hash,
        invariants: ['pgvector:install-vector-v1'],
      },
      '../../snapshots',
    ),
    'migrations/pgvector/refs/head.json': ref(vector.hash, ['pgvector:install-vector-v1']),
  };
}

function extensionPackage(format: Format): Record<string, string> {
  const vector = contractFiles(pgvectorSpace, format);
  return {
    'src/contract.json': emittedJson(vector.contract),
    'src/contract.d.ts': vector.dts,
    [`migrations/snapshots/${vector.hash}/contract.json`]: snapshotJson(vector.contract),
    [`migrations/snapshots/${vector.hash}/contract.d.ts`]: vector.dts,
    ...migrationFiles(
      {
        dir: 'migrations/20260601T0000_install_vector_extension',
        from: null,
        to: vector.hash,
        invariants: ['pgvector:install-vector-v1'],
        migrationTs: true,
      },
      '../snapshots',
    ),
    'migrations/refs/head.json': ref(vector.hash, ['pgvector:install-vector-v1']),
  };
}

const sqliteSettings: ContractSpec = {
  target: 'sqlite',
  tables: {
    setting: [
      {
        name: 'id',
        codecId: 'sqlite/integer@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
        literalDefault: { old: 0, new: '0', oldTs: '0', newTs: "'0'" },
      },
      {
        name: 'count',
        codecId: 'sql/int@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
        literalDefault: { old: 42, new: '42', oldTs: '42', newTs: "'42'" },
      },
      {
        name: 'big',
        codecId: 'sqlite/bigint@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
        literalDefault: {
          old: '9007199254740993',
          new: '9007199254740993',
          oldTs: "'9007199254740993'",
          newTs: "'9007199254740993'",
        },
      },
      {
        name: 'small',
        codecId: 'sqlite/bigintnumber@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
        literalDefault: { old: -7, new: '-7', oldTs: '-7', newTs: "'-7'" },
      },
      {
        name: 'doc',
        codecId: 'sqlite/json@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: false,
        literalDefault: {
          old: { a: [true, null], b: 1 },
          new: '{"a":[true,null],"b":1}',
          oldTs: '{ readonly a: readonly [true, null]; readonly b: 1 }',
          newTs: `'{"a":[true,null],"b":1}'`,
        },
      },
      {
        name: 'label',
        codecId: 'sqlite/json@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: false,
        literalDefault: { old: "it's", new: `"it's"`, oldTs: `"it's"`, newTs: `'"it\\'s"'` },
      },
      {
        name: 'empty',
        codecId: 'sqlite/json@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: true,
        literalDefault: { old: null, new: 'null', oldTs: 'null', newTs: "'null'" },
      },
      {
        name: 'name',
        codecId: 'sqlite/text@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: false,
        literalDefault: { old: 'unnamed', new: 'unnamed', oldTs: "'unnamed'", newTs: "'unnamed'" },
      },
      {
        name: 'ratio',
        codecId: 'sqlite/real@1',
        nativeType: 'real',
        dataType: 'sqlite/real',
        nullable: false,
        literalDefault: { old: 1.5, new: 1.5, oldTs: '1.5', newTs: '1.5' },
      },
      {
        name: 'seenAt',
        codecId: 'sqlite/datetime@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: true,
      },
      {
        name: 'payload',
        codecId: 'sqlite/blob@1',
        nativeType: 'blob',
        dataType: 'sqlite/blob',
        nullable: true,
      },
      {
        name: 'code',
        codecId: 'sql/char@1',
        nativeType: 'character',
        dataType: 'sqlite/character',
        nullable: true,
      },
      {
        name: 'tag',
        codecId: 'sql/varchar@1',
        nativeType: 'character varying',
        dataType: 'sqlite/character-varying',
        nullable: true,
      },
      {
        name: 'score',
        codecId: 'sql/float@1',
        nativeType: 'real',
        dataType: 'sqlite/real',
        nullable: true,
      },
    ],
  },
};

function sqliteDefaults(format: Format): Record<string, string> {
  const settings = contractFiles(sqliteSettings, format);
  return {
    'src/prisma/contract.json': emittedJson(settings.contract),
    'src/prisma/contract.d.ts': settings.dts,
    [`migrations/snapshots/${settings.hash}/contract.json`]: snapshotJson(settings.contract),
    [`migrations/snapshots/${settings.hash}/contract.d.ts`]: settings.dts,
    ...migrationFiles(
      {
        dir: 'migrations/app/20260101T0000_initial',
        from: null,
        to: settings.hash,
        migrationTs: true,
      },
      '../../snapshots',
    ),
    'migrations/app/refs/head.json': ref(settings.hash),
  };
}

const integerMember = (name: string, value: number) => ({
  name,
  old: value,
  new: String(value),
  oldTs: String(value),
  newTs: `'${value}'`,
});

const sqliteEnums: ContractSpec = {
  target: 'sqlite',
  tables: {
    post: [
      {
        name: 'id',
        codecId: 'sqlite/integer@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
      },
      {
        name: 'priority',
        codecId: 'sqlite/integer@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
        valueSet: 'Priority',
        literalDefault: { old: 1, new: '1', oldTs: '1', newTs: "'1'" },
      },
      {
        name: 'level',
        codecId: 'sql/int@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: true,
        valueSet: 'Level',
      },
      {
        name: 'mood',
        codecId: 'sqlite/text@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: true,
        valueSet: 'Mood',
      },
    ],
  },
  enums: [
    {
      name: 'Level',
      codecId: 'sql/int@1',
      members: [integerMember('Debug', -1), integerMember('Info', 0)],
    },
    {
      name: 'Mood',
      codecId: 'sqlite/text@1',
      members: [{ name: 'Calm', old: 'calm', new: 'calm', oldTs: "'calm'", newTs: "'calm'" }],
    },
    {
      name: 'Priority',
      codecId: 'sqlite/integer@1',
      members: [integerMember('Low', 1), integerMember('High', 2)],
    },
  ],
};

function sqliteIntegerEnums(format: Format): Record<string, string> {
  return singleSpaceProject(sqliteEnums, format, 'prisma', 'migrations');
}

const jsonMember = (name: string, value: Json, oldTs: string) => ({
  name,
  old: value,
  new: JSON.stringify(value),
  oldTs,
  newTs: `'${JSON.stringify(value)}'`,
});

const sqliteJsonEnumSpec: ContractSpec = {
  target: 'sqlite',
  tables: {
    lamp: [
      {
        name: 'id',
        codecId: 'sqlite/integer@1',
        nativeType: 'integer',
        dataType: 'sqlite/integer',
        nullable: false,
      },
      {
        name: 'shade',
        codecId: 'sqlite/json@1',
        nativeType: 'text',
        dataType: 'sqlite/text',
        nullable: false,
        valueSet: 'Shade',
        literalDefault: { old: 'low', new: '"low"', oldTs: "'low'", newTs: `'"low"'` },
      },
    ],
  },
  enums: [
    {
      name: 'Shade',
      codecId: 'sqlite/json@1',
      members: [
        jsonMember('Low', 'low', "'low'"),
        jsonMember('Level', 1, '1'),
        jsonMember('On', true, 'true'),
        jsonMember('Unset', null, 'null'),
      ],
    },
  ],
};

function sqliteJsonEnums(format: Format): Record<string, string> {
  return singleSpaceProject(sqliteJsonEnumSpec, format, 'prisma', 'migrations');
}

const unknownCodecSpec: ContractSpec = {
  target: 'postgres',
  tables: {
    thing: [
      {
        name: 'id',
        codecId: 'pg/uuid@1',
        nativeType: 'uuid',
        dataType: 'pg/uuid',
        nullable: false,
      },
      {
        name: 'shape',
        codecId: 'acme/shape@1',
        nativeType: 'shape',
        dataType: 'acme/shape',
        nullable: true,
      },
    ],
  },
};

function unknownCodec(format: Format): Record<string, string> {
  const thing = contractFiles(unknownCodecSpec, format);
  return {
    'prisma/contract.json': emittedJson(thing.contract),
    'prisma/contract.d.ts': thing.dts,
    [`migrations/snapshots/${thing.hash}/contract.json`]: snapshotJson(thing.contract),
    [`migrations/snapshots/${thing.hash}/contract.d.ts`]: thing.dts,
    ...migrationFiles(
      { dir: 'migrations/app/20260101T0000_initial', from: null, to: thing.hash },
      '../../snapshots',
    ),
  };
}

const acmeSpec: ContractSpec = {
  target: 'acme',
  tables: {
    thing: [
      {
        name: 'id',
        codecId: 'sql/int@1',
        nativeType: 'int4',
        dataType: 'acme/int4',
        nullable: false,
      },
    ],
  },
};

function unknownTarget(format: Format): Record<string, string> {
  const thing = contractFiles(acmeSpec, format);
  return {
    'prisma/contract.json': emittedJson(thing.contract),
    'prisma/contract.d.ts': thing.dts,
    [`migrations/snapshots/${thing.hash}/contract.json`]: snapshotJson(thing.contract),
    [`migrations/snapshots/${thing.hash}/contract.d.ts`]: thing.dts,
    ...migrationFiles(
      { dir: 'migrations/app/20260101T0000_initial', from: null, to: thing.hash },
      '../../snapshots',
    ),
  };
}

const userSpec: ContractSpec = {
  target: 'postgres',
  tables: {
    user: [
      {
        name: 'id',
        codecId: 'pg/uuid@1',
        nativeType: 'uuid',
        dataType: 'pg/uuid',
        nullable: false,
      },
      {
        name: 'email',
        codecId: 'pg/text@1',
        nativeType: 'text',
        dataType: 'pg/text',
        nullable: false,
      },
    ],
  },
};

function snapshotCollision(): Record<string, string> {
  const old = contractFiles(userSpec, 'old');
  const upgraded = contractFiles(userSpec, 'new');
  return {
    [`migrations/snapshots/${old.hash}/contract.json`]: snapshotJson(old.contract),
    [`migrations/snapshots/${old.hash}/contract.d.ts`]: old.dts,
    [`migrations/snapshots/${upgraded.hash}/contract.json`]: snapshotJson(upgraded.contract),
    [`migrations/snapshots/${upgraded.hash}/contract.d.ts`]: 'export {};\n',
    ...migrationFiles(
      { dir: 'migrations/app/20260101T0000_initial', from: null, to: old.hash },
      '../../snapshots',
    ),
  };
}

function snapshotAlreadyPresent(format: Format): Record<string, string> {
  const old = contractFiles(userSpec, 'old');
  const upgraded = contractFiles(userSpec, 'new');
  const files: Record<string, string> = {
    [`migrations/snapshots/${upgraded.hash}/contract.json`]: snapshotJson(upgraded.contract),
    [`migrations/snapshots/${upgraded.hash}/contract.d.ts`]: upgraded.dts,
    ...migrationFiles(
      {
        dir: 'migrations/app/20260101T0000_initial',
        from: null,
        to: format === 'old' ? old.hash : upgraded.hash,
      },
      '../../snapshots',
    ),
  };
  if (format === 'old') {
    files[`migrations/snapshots/${old.hash}/contract.json`] = snapshotJson(old.contract);
    files[`migrations/snapshots/${old.hash}/contract.d.ts`] = old.dts;
  }
  return files;
}

const invoiceSpec: ContractSpec = {
  target: 'postgres',
  tables: {
    invoice: [
      {
        name: 'id',
        codecId: 'pg/uuid@1',
        nativeType: 'uuid',
        dataType: 'pg/uuid',
        nullable: false,
      },
      {
        name: 'amount',
        codecId: 'pg/numeric@1',
        nativeType: 'numeric',
        dataType: 'pg/numeric',
        nullable: false,
        typeParams: { precision: 10, scale: 2 },
      },
    ],
  },
};

function singleSpaceProject(
  spec: ContractSpec,
  format: Format,
  contractDir: string,
  migrationsDir: string,
): Record<string, string> {
  const files = contractFiles(spec, format);
  return {
    [`${contractDir}/contract.json`]: emittedJson(files.contract),
    [`${contractDir}/contract.d.ts`]: files.dts,
    [`${migrationsDir}/snapshots/${files.hash}/contract.json`]: snapshotJson(files.contract),
    [`${migrationsDir}/snapshots/${files.hash}/contract.d.ts`]: files.dts,
    ...migrationFiles(
      {
        dir: `${migrationsDir}/app/20260101T0000_initial`,
        from: null,
        to: files.hash,
        migrationTs: true,
      },
      '../../snapshots',
    ),
    [`${migrationsDir}/app/refs/head.json`]: ref(files.hash),
  };
}

function dbMigrations(format: Format): Record<string, string> {
  return singleSpaceProject(userSpec, format, 'db', 'db/migrations');
}

function twoMigrationRoots(format: Format): Record<string, string> {
  return {
    ...singleSpaceProject(userSpec, format, 'db', 'db/migrations'),
    ...singleSpaceProject(invoiceSpec, format, 'billing', 'billing/history'),
  };
}

const olderLayoutSpec: ContractSpec = { ...userSpec, layout: 'tables' };

function staleHash(format: Format): Record<string, string> {
  const stale = contractFiles(olderLayoutSpec, format, format === 'old' ? STALE_HASH : undefined);
  return {
    [`migrations/snapshots/${stale.hash}/contract.json`]: snapshotJson(stale.contract),
    [`migrations/snapshots/${stale.hash}/contract.d.ts`]: stale.dts,
    ...migrationFiles(
      {
        dir: 'migrations/app/20260101T0000_initial',
        from: null,
        to: stale.hash,
        migrationTs: true,
      },
      '../../snapshots',
    ),
    'migrations/app/refs/head.json': ref(stale.hash),
  };
}

const documentWithTypeName = "{ readonly codecId: 'pg/text@1'; readonly nativeType: 'text' }";

const jsonDocumentSpec: ContractSpec = {
  target: 'postgres',
  tables: {
    setting: [
      {
        name: 'id',
        codecId: 'pg/uuid@1',
        nativeType: 'uuid',
        dataType: 'pg/uuid',
        nullable: false,
      },
      {
        name: 'payload',
        codecId: 'pg/jsonb@1',
        nativeType: 'jsonb',
        dataType: 'pg/jsonb',
        nullable: false,
        literalDefault: {
          old: { codecId: 'pg/text@1', nativeType: 'text' },
          new: { codecId: 'pg/text@1', nativeType: 'text' },
          oldTs: documentWithTypeName,
          newTs: documentWithTypeName,
        },
      },
    ],
  },
};

function jsonDefaultDocument(format: Format): Record<string, string> {
  const files = contractFiles(jsonDocumentSpec, format);
  return {
    'prisma/contract.json': emittedJson(files.contract),
    'prisma/contract.d.ts': files.dts,
  };
}

rmSync(fixturesRoot, { recursive: true, force: true });
writeCase('postgres-extension-space', postgresExtensionSpace);
writeCase('extension-package', extensionPackage);
writeCase('sqlite-defaults', sqliteDefaults);
writeCase('snapshot-already-present', snapshotAlreadyPresent);
writeCase('stale-hash', staleHash);
writeCase('unknown-codec', unknownCodec);
writeCase('unknown-target', unknownTarget);
writeCase('db-migrations', dbMigrations);
writeCase('two-migration-roots', twoMigrationRoots);
writeCase('sqlite-integer-enums', sqliteIntegerEnums);
writeCase('sqlite-json-enums', sqliteJsonEnums);
writeCase('json-default-document', jsonDefaultDocument);
writeUnchangedCase('snapshot-collision', snapshotCollision());
